#!/usr/bin/env bash
python ./scripts/install-agent.py \
    -s app_agents/InterfaceAgent \
    -i interface_bestest_air \
    --tag interface_bestest_air \
    --config config/interface_config_bestest_air \
    --start \
    --force
