#!/usr/bin/env bash
python ./scripts/install-agent.py \
    -s app_agents/InterfaceAgent \
    -i interface_3147 \
    --tag interface_3147 \
    --config config/interface_config_3147 \
    --start \
    --force
