FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY test/server_ecobee.py test/ecobee.py /app/

RUN pip install --no-cache-dir flask flask-restful requests
EXPOSE 5005
CMD ["python", "/app/server_ecobee.py"]
