#!/usr/bin/env bash
# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s app_agents/RecvAgent \
    -i rec_ecobee \
    --tag rec_ecobee \
    --config config/recv_config_ecobee \
    --start \
    --force
