#!/usr/bin/env bash
# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s app_agents/RecvAgent \
    -i rec \
    --tag rec \
    --config config/recv_config \
    --start \
    --force
