#!/usr/bin/env bash
# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s app_agents/InterfaceAgent \
    -i interface_bestest_hydronic \
    --tag interface_bestest_hydronic \
    --config config/interface_config_bestest-hydronic \
    --start \
    --force
