#!/usr/bin/env bash
# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s app_agents/InterfaceAgent \
    -i interface_bacnet \
    --tag interface_bacnet \
    --config config/interface_config_bacnet \
    --start \
    --force
